# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Chapter Number')),
                ('title', models.CharField(max_length=200, verbose_name='Chapter Title')),
                ('content', models.TextField()),
                ('link', models.URLField(verbose_name='link to source')),
                ('translated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False, verbose_name='ready to be posted')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, verbose_name='First Name')),
                ('last', models.CharField(max_length=30, verbose_name='Last Name')),
                ('persona', models.CharField(max_length=30, verbose_name='Displayed Name')),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Translated Title')),
                ('jptitle', models.CharField(max_length=100, verbose_name='Japanese Title')),
                ('jpengtitle', models.CharField(max_length=100, verbose_name='Japanese Title (Romaji)')),
                ('author', models.CharField(max_length=25, verbose_name='Japanese Author')),
                ('summary', models.TextField()),
                ('editors', models.ManyToManyField(blank=True, to='translations.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, verbose_name='First Name')),
                ('last', models.CharField(max_length=30, verbose_name='Last Name')),
                ('persona', models.CharField(max_length=30, verbose_name='Displayed Name')),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='translators',
            field=models.ManyToManyField(blank=True, to='translations.Translator'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Project'),
        ),
    ]
