# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

def slug_existing_entries(apps, schema_editor):
    Post = apps.get_model("translations", "Post")
    for post in Post.objects.all():
        slug = slugify(post.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        # if > 50 then cut so it is first 50 of title - unique number + hyphen
        # then add number and hyphen back to string
        if len(unique_slug) > 50:
            unique_slug = unique_slug[:50-(num+1)]
            unique_slug = '{}-{}'.format(unique_slug, num)
        post.slug = unique_slug
        post.save()

    Project = apps.get_model("translations", "Project")
    for project in Project.objects.all():
        project.slug = slugify(project.title)
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(slug_existing_entries),
    ]
